on: push
jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
          swiftenv install 5.5
      - run: swift test
